In [ ]:
import numpy

In [1]:
import numpy as ny

In [ ]:
a=ny.array([(1,2,3,4,),(1,2,4,5),(7,6,5,8)])

In [ ]:
print(a)

In [ ]:
trans=ny.transpose(a)

In [ ]:
print(trans)

In [ ]:
trans.ravel()

In [2]:
zero=ny.ones((5,5))

In [3]:
print(zero)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
ny.random.random((2,2))

array([[0.04214103, 0.54922585],
       [0.58252408, 0.3047011 ]])

numpy